### ISSUE TITLE
Issue with accessing FHIR Data types

### ISSUE THREAD

**Issue by darena-pjindal** [google/cql#59]
Hello - I have been trying some very simple queries but it seems to not recognize the basic FHIR types. Am I don't something wrong here? Here is one of the query I tried. 

library SampleTest version '0.0.1'

using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers

context Patient

define "IsMale":
  Patient.gender = 'male'

define "HasHypertension":
  exists (
    [Observation] O
      where exists (O.code.coding C where C.code = 'sys-bld-prs')
        and O.value is Quantity
        and O.value.value > 140
  )

define "HasGlucoseObservation":
  exists (
    [Observation] O
      where exists (O.code.coding C where C.code = 'gluc')
  )

define "MeetsCriteria":
     "IsMale"
    and "HasHypertension"

define "Recommendation":
  if "MeetsCriteria" then 'Recommend monitoring blood pressure and lifestyle changes'
  else 'No specific recommendation'

define "Rationale":
  if "MeetsCriteria" then 'Patient meets criteria for hypertension monitoring'
  else 'Patient does not meet criteria for hypertension monitoring'

define "Errors":
  null

**Comment by evan-gordon** [comment]
Hi @darena-pjindal 

Thank you for taking the time to open an issue!

I'm using the cqlplayground to tinker around a bit with the code you linked and I have found a few things but I'm still working on a getting you a proper response. So changing `and O.value is Quantity` to `and O.value is FHIR.Quantity` should make that part of the query filter properly.

I think there may be a bug in the engine regarding the conversion of said FHIR.Quantity into a system type that you can compare the value of, but I'm not quite done looking into that at this time.

I'll try to get you an update on this as soon as i can but since it's almost the weekend no promises before Monday :)
If you could add any error outputs from the engine to the ticket that would also be helpful!

**Comment by darena-pjindal** [comment]
Thanks, @evan-gordon, for the quick response. Let me know if I can help to provide more details. Thanks for creating such a great tool!

**Comment by suyashkumar** [comment]
Hi @darena-pjindal, I had some free time and was able to do a lil investigation. It turns out this has to do with a discrepancy in how FHIR protocol buffers represent decimals and how the CQL FHIR ModelInfo statically expects decimal.value properties to behave. #60 should fix the issue you were facing in "HasHypertension" with the following modifications:

```
and O.value is FHIR.Quantity
and (O.value as FHIR.Quantity).value > 140
```

```
define "HasHypertension":
exists (
[Observation] O
where exists (O.code.coding C where C.code = 'sys-bld-prs')
and O.value is FHIR.Quantity
and (O.value as FHIR.Quantity).value > 140
)
```

I think there's at least one other bug or improvement to be made here, but hopefully this should unblock your explorations!

**Comment by darena-pjindal** [comment]
Thanks @suyashkumar. That worked

**Comment by suyashkumar** [comment]
Awesome, great to hear! Let us know if you run into any other issues.

**Comment by darena-pjindal** [comment]
@suyashkumar—Actually, I am still having a conversion issue. I don't remember what query I tried over the weekend, but this doesn't seem to work. It says Error: failed to eval: failed during CQL evaluation: Explore 1.2.3, internal error—can not convert System.String to a float64. 

library Explore version '1.2.3'
using FHIR version '4.0.1'

include FHIRHelpers version '4.0.1' called FHIRHelpers

context Patient

define "IsMale":
Patient.gender = 'male'


define "HasHypertension":
exists (
[Observation] O
where exists (O.code.coding C where C.code = 'sys-bld-prs')
and O.value is FHIR.Quantity
and (O.value as FHIR.Quantity).value > 140
)

**Comment by suyashkumar** [comment]
@darena-pjindal are you using the latest commit on main that includes my PR #60? I'm able to get it to work in the playground with default data at HEAD.
<img width="789" alt="Screenshot 2024-08-05 at 12 20 17 PM" src="https://github.com/user-attachments/assets/b6184a26-e6fd-4708-8349-1b58565d5370">

**Comment by suyashkumar** [comment]
No problem at all, glad it's working! Thanks again for giving our tools a try--please do open any more issues that you run into in the future!

**Comment by evan-gordon** [comment]
Glad to hear you're unblocked @darena-pjindal ! Let us know if anything else comes up!

@suyashkumar thanks for your quick work here!

Closing the issue as resolved.
